### ISSUE TITLE
Create Contact profile 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#1]
## Value statement 
As a **user** 
I want to **have contact cards** 
so **I can see all contact information** 

## Description (Text, Scribble, Wireframe, Design)
A page with all contact information: Name, company, contact information, notes and a picture of the business card. 

## Acceptance criteria
- [x] The form is found at the path `/contact/{id}`
- [x] Overview of the contact information 
- [x] Show tags 
- [x] Toggle area with all contact information 
- [x] Toggle area with notes 

## Tasks
- [x] Create feature branch 
- [x] Create component in storybook 
- [x] Create contact card 
- [x] Create tags 
- [x] Create contact information
- [x] Create notes 

## Complexity
medium

### Wireframe 
![contact-card](https://user-images.githubusercontent.com/67868341/91314938-62bff480-e7b7-11ea-80d0-3067bc8b0f3b.png)
