### ISSUE TITLE
Exhibitor profile 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#10]
## Value statement 
As a **user** 
I need **more information about a single exhibitor** 
so I can **decide whether it is relevant and mark him** 

## Description 
A profile Information about stand positions, general information about the company and the option to add the profile to favorites. 

## Acceptance criteria
- [ ] Show the position of the exhibitor  
- [ ] Show further information about the company 
- [ ] Show announcements of the company 

## Tasks
- [ ] Create a profile for exhibitors 
- [ ] Add bookmark function

## Complexity
small

## Wireframe 
![exhibitor-profile](https://user-images.githubusercontent.com/67868341/91319793-124b9580-e7bd-11ea-9367-837c953f8f0d.png)
