### ISSUE TITLE
Create contact

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#13]
## Value statement 
As a **user** 
I need **a feature to create contacts** 
so **I can add them to my contact list** 

## Description
A page with inputs to add contacts.

## Acceptance criteria
- [x] The form is found at the patch `/create`
- [x] Shows inputs for name, company, notes and tags
- [x] The button is disabled until first name, last name or company are filled to avoid empty data sets
- [x] The form is cleared after submit 
- [x] 'First name' is focused after submit
- [x] The button will be deactivated after submit 

## Tasks
- [x] Create feature branch 
- [x] Create component in storybook 
- [x] Create a page with inputs to add contacts 
- [x] Write tests

## Complexity
medium
