### ISSUE TITLE
Edit user profile 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#14]
## Value statement 
As a **user** 
I need **a form** 
so **I can add contact information to my profile** 

## Description (Text, Scribble, Wireframe, Design)
A page to fill the users profile with information to share it with other people. 

## Acceptance criteria
- [ ] The form is found at the path `/profile/edit`
- [ ] Show button to add a profile picture 
- [ ] Show inputs for contact information 
- [ ] Name of the user and the company are required 

## Tasks

- [x] Create feature branch 
- [x] Add button to add a profile picture 
- [x] Add inputs to insert the contact information 
- [x] Add "Edit profile" button to user profile 

## Complexity
medium
