### ISSUE TITLE
Create header component 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#19]
## Value statement 
As a **user** 
I need **a header with buttons for navigation** 
so that **I can navigate between different features ** 

## Description (Text, Scribble, Wireframe, Design)
![92451700-60996500-f1bd-11ea-81f1-6aa3656d290c](https://user-images.githubusercontent.com/67868341/93203189-44b13880-f754-11ea-9317-42f098bb8bf6.jpg)

## Acceptance criteria
- [x] Show 'back', 'profile' and 'favorites' on every page except the homepage

## Tasks
- [x] Create feature branch 
- [x] Create component in storybook
- [x] Add icons 
- [x] Add paths 

## Complexity
small
