### ISSUE TITLE
Create Homepage with navigation 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#2]
## Value statement 
As a **user** 
I need **a homepage** 
so **I can navigate between the functions** 

## Description 
Homepage with navigation and access to your profile and search. 

## Acceptance criteria
- [x] Show navigation and buttons  for profile and search
- [x] Show "Hello, 'Name of the user'!" 
- [x] Show buttons "All contacts" and "Favorites"

## Tasks
- [x] Create Navigation 
- [x] Add 'Add contact' to navigation 
- [x] Add 'Contact list' to navigation 
- [x] Add 'Favorite Contacts' to navigation   
- [x] Add 'Profile' to navigation   
- [x] Test on mobile 

## Complexity
medium

### Wireframe 
![Wireframes Gesellenstück-16](https://user-images.githubusercontent.com/67868341/92454164-83794880-f1c0-11ea-8991-144bd9bdac52.jpg)

**Comment by jennydely** [comment]
All buttons are working and the urls  render correct
