### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#21]
## Value statement 
As a **user** 
I need **localStorage** 
so that **I can also access the data after a reload** 

## Description 
The contact data should be stored in localStorage so that the user can access it even after a reload. 

## Acceptance criteria
- [x] The contact data should be stored in localstorage 
- [x] The data should be displayed again after a reload 

## Tasks
- [x] Create feature branch 
- [x] Add local storage 

## Complexity
small
