### ISSUE TITLE
Create Contact list 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#3]
## Value statement 
As a **user** 
I need **an overview of my contacts** 
so **I can search for them** 

## Description (Text, Scribble, Wireframe, Design)
A list of all contacts that have been added during the fair. 

## Acceptance criteria
- [x] The list is found at the path `/contacts`
- [x] Show all contacts 
- [x] Show the company and the name of a contact 
- [x] long names are shortened

## Tasks
- [x] Create feature branch 
- [x] Create component in storybook 
- [x] Create a page with contact information 
- [x] Create a list from cards 

## Complexity
small

### Wireframe 
![Wireframes Gesellenstück-12](https://user-images.githubusercontent.com/67868341/91587623-52468000-e957-11ea-900a-5288ca04e83e.jpg)
