### ISSUE TITLE
QR-Scanner

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#31]
## Value statement

As a **user**
I need **a QR-Scanner**
so I **can scan QR-Codes and import contact information**

## Acceptance criteria

- [ ] Show a button to open QR-Scanner
- [ ] Add button to contact form 
- [ ] Import data to contact list 

## Tasks
- [x] Create a feature branch 
- [x] Add QR-Scanner component

## Complexity
medium
