### ISSUE TITLE
Create Favorite contacts list

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#4]
## Value statement 
As a **user** 
I need **an overview of my favorite contacts** 
so **I can better search for them** 

## Description
A list of all contacts that have been bookmarked during the fair. 

## Acceptance criteria
- [x] Show all bookmarked contacts 
- [x] Bookmarks can be deleted 
- [x] Way to get back to all contacts
- [x] Show "You have not yet added any contacts to favorites" if no contacts have been favorized yet 

## Tasks
- [x] Create a list with bookmarked contacts 
- [x] Get the contacts from the contact-list when they are bookmarked  

## Complexity
small

### Wireframe 
![Wireframes Gesellenstück-11](https://user-images.githubusercontent.com/67868341/91587676-64c0b980-e957-11ea-993d-d4886ec15e8a.jpg)
