### ISSUE TITLE
Add User Profile 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#6]
## Value statement 
As a **user** 
I need **a profile** 
so **I can store my own contact information** 

## Description
A profile with a picture of yourself and other contact information. Additionally a button to share the contact information as a digital business card. 

## Acceptance criteria
- [x] Show contact information 
- [x] Welcome on the homepage based on the user data 

## Tasks
- [x] Create a profile page 
- [x] Add a form to create a personal profile 
- [x] The form should only be displayed if the user has not yet added any data
- [x] The user can change the data with an edit button
- [x] After submitting the user will be redirected to the profile

## Complexity
medium

## Wireframe 
![Wireframes Gesellenstück-17](https://user-images.githubusercontent.com/67868341/93078179-5a5a2b80-f68a-11ea-9994-0a22f5876848.jpg)
