### ISSUE TITLE
Share digital business card 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#7]
## Value statement 
As a **user** 
I need **a feature** 
so **I can share my contact information as digital business card** 

## Acceptance criteria
- [ ] Generate and show QR-Code 
- [ ] Store csv-file in QR-Code 
- [ ] Show QR-Code 

## Tasks
- [ ] (todos for the team)
- [ ] 
- [ ] 
## Complexity
(small, medium, large)
