### ISSUE TITLE
Share vCard 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#8]
## Value statement 
As a **user** 
I need **a feature** 
so **I can share my contact information as digital business card** 

## Acceptance criteria
- [x] Generate and show QR-Code 
- [x] Store csv-file in QR-Code 
- [x] Show QR-Code 
- [x] Button to edit data 
- [x] Return to profile when data has been edited 

## Tasks
- [x] Create a page for the sharing-feature
- [x] Generate and display QR-code from csv file
- [x] Add feature to the profile

## Complexity
high

## Wireframe 
![Wireframes Gesellenstück-17 2](https://user-images.githubusercontent.com/67868341/93190518-c3ea4080-f743-11ea-8759-4e49d3cf3923.jpg)
