### ISSUE TITLE
Exhibitors list 

### ISSUE THREAD

**Issue by soerenstein** [soerenstein/capstone-project#9]
## Value statement 
As a **user** 
I need **a list of all exhibitors** 
so **I can can plan my visit to the fair** 

## Description 
A list of all exhibitors with the possibility to filter mark individual favorites.

## Acceptance criteria
- [ ] Show all exhibitors 
- [ ] Show more information in exhibitor profile 

## Tasks
- [ ] Create list of all exhibitors 
- [ ] Add filter function

## Complexity
small

## Wireframe 
![exhibitors-list](https://user-images.githubusercontent.com/67868341/91318174-3b6b2680-e7bb-11ea-8df9-b186a8264416.png)
